
---
apiVersion: v1
kind: Service
metadata:
  name: insighttellers-web-clusterip-{{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.name }}
